version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'zokrates.blockchain-it.hr -> http://zokrates:10000, dev.zokrates.blockchain-it.hr -> http://zokrates-dev:10000'
      STAGE: 'production'
    container_name: nginx
    networks:
      - zokrates

  zokrates:
    image: blockchainit/zokrates-remix-plugin:stable
    ports:
      - 10000:10000
    container_name: zokrates
    networks:
      - zokrates

  zokrates-dev:
    image: blockchainit/zokrates-remix-plugin:latest
    ports:
      - 11000:10000
    container_name: zokrates-dev
    networks:
      - zokrates     

networks:
  zokrates:
