version: 2
general:
  branches:
    only:
      - feature-ci
      - master
      - develop
jobs:
  build:
    docker:
      - image: circleci/node 
    working_directory: ~/zokrates
    steps:
      - checkout
      - setup_remote_docker
      - run: echo mandrilo | docker login --username ijsfd --password-stdin
      - run: docker build --file Dockerfile.dev --tag blockchainit/zokrates.js:dev .
      - run: docker build --file Dockerfile --tag blockchainit/zokrates.js:stable .
      - run: docker push blockchainit/zokrates.js
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: zokrates