version: 2
general:
  branches:
    only:
      - feature-ci
      - master
      - develop
jobs:
  build:
    docker:
      - image: circleci/node 
    working_directory: ~/zokrates
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - run: |
          if [ $CIRCLE_BRANCH=="develop" ]; then export TAG="latest"; fi
          if [ $CIRCLE_BRANCH=="feature-ci" ]; then export TAG="latest"; fi
          if [ $CIRCLE_BRANCH=="master" ]; then export TAG="stable"; fi
          echo $TAG
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: zokrates