version: 2
general:
  branches:
    only:
      - feature-ci
      - master
      - develop
jobs:
  build:
    docker:
      - image: circleci/node 
    working_directory: ~/zokrates
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build --file Dockerfile --tag blockchainit/zokrates.js:stable .
          docker push blockchainit/zokrates.js:stable
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: zokrates