version: 2
general:
  branches:
    only:
      - react
jobs:
  build:
    docker:
      - image: circleci/node 
    working_directory: ~/zokrates
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker build --file Dockerfile.dev --tag blockchainit/zokrates.js:dev
          docker build --file Dockerfile --tag blockchainit/zokrates.js:stable
          docker push blockchainit/zokrates.js
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: zokrates